CREATE TABLE USER
(
    user_id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name   VARCHAR(255)                         NOT NULL,
    email       VARCHAR(255)                         NOT NULL,
    university  VARCHAR(100),
    user_degree VARCHAR(100),
    phoneNumber VARCHAR(100)                         NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE WALLET
(
    wallet_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   VARCHAR(255)                         NOT NULL,
    credit    DOUBLE DEFAULT 0.0,
    PRIMARY KEY (wallet_id),
    FOREIGN KEY (user_id) REFERENCES USER (user_id)
);

CREATE TABLE TAG
(
    tag_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_name VARCHAR(255)                         NOT NULL,
    PRIMARY KEY (tag_id)
);

CREATE TABLE TOPIC
(
    topic_id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          INT                                  NOT NULL,
    topic_name       VARCHAR(255)                         NOT NULL,
    description      VARCHAR(512)                         NOT NULL,
    credit_per_hr    DOUBLE                               NOT NULL,
    experience_level DOUBLE                               NOT NULL,
    overall_rating   DOUBLE                               NOT NULL,
    PRIMARY KEY (topic_id),
    FOREIGN KEY (user_id) REFERENCES USER (user_id)
);

CREATE TABLE TOPIC_TAGS
(
    topic_tag_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    topic_id     INT                                  NOT NULL,
    tag_id       INT                                  NOT NULL,
    PRIMARY KEY (topic_tag_id),
    FOREIGN KEY (topic_id) REFERENCES TOPIC (topic_id),
    FOREIGN KEY (tag_id) REFERENCES TAGS (tag_id)
);

CREATE TABLE RATING
(
    rating_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     INT                                  NOT NULL,
    tutor_id    INT                                  NOT NULL,
    topic_id    INT                                  NOT NULL,
    description VARCHAR(512)                         NOT NULL,
    rating      DOUBLE                               NOT NULL,
    PRIMARY KEY (rating_id),
    FOREIGN KEY (user_id) REFERENCES USER (user_id),
    FOREIGN KEY (tutor_id) REFERENCES USER (user_id),
    FOREIGN KEY (topic_id) REFERENCES TOPIC (topic_id)
);

CREATE TABLE USER_SLOTS
(
    slot_id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           INT                                  NOT NULL,
    topic_id          INT                                  NOT NULL,
    slot_date         DATE                                 NOT NULL,
    start_time        DATE                                 NOT NULL,
    end_time          DATE                                 NOT NULL,
    is_booked         CHAR                                 NOT NULL,
    booked_by_user_id INT                                  NOT NULL,
    PRIMARY KEY (slot_id),
    FOREIGN KEY (user_id) REFERENCES USER (user_id),
    FOREIGN KEY (topic_id) REFERENCES TOPIC (topic_id),
    FOREIGN KEY (booked_by_user_id) REFERENCES USER (user_id)
);