<html>
    <head></head>
    <body>
        <p>Dear ${student},</p>
        <p><b>Your session with ${tutor} has been confirmed!</b></p>
        <p>Slot Details -</p>
            <p>&emsp; Date : ${slotDate}</p>
            <p>&emsp; Time : ${startTime} to ${endTime}</p>
        <p>You can reach your tutor by </p>
            <p>&emsp; Email : ${email}</p>
            <p>&emsp; Phone : ${phone}</p>
        <p>Thanks!</p>
        <p>AppName Admin Team</p>
        <hr>
        <p>Have questions or need help? Email us at ${adminEmail}</p>
        <p>${dateNow}</p>
    </body>
</html>